/**
 * Predefined CONSTANTS for using cross through project
 *
 * @author Long Pham
 * @type {*|start}
 */

const CONSTANT = {
  AUTH_HEADER_KEY: 'authorization',
  AUTH_HEADER_SCHEME: 'Bearer',

  // HTTP STATUS CODES
  HTTP_STATUS_OK: 200,
  HTTP_STATUS_BAD_REQUEST: 400,
  HTTP_STATUS_UNAUTHORIZED: 401,
  HTTP_STATUS_FORBIDDEN: 403,
  HTTP_STATUS_NOT_FOUND: 404,
  HTTP_STATUS_METHOD_NOT_ALLOWED: 405,
  HTTP_STATUS_NOT_ACCEPTABLE: 406,
  HTTP_STATUS_CONFLICT: 409,
  HTTP_STATUS_PAYLOAD_TOO_LARGE: 413,
  HTTP_STATUS_LOCKED: 423,
  HTTP_STATUS_TOO_MANY_REQUEST: 429,
  HTTP_STATUS_INTERNAL_SERVER_ERROR: 500,
  HTTP_STATUS_NOT_IMPLEMENTED:501,
  HTTP_STATUS_BAG_GATEWAY: 502,
  HTTP_STATUS_SERVICE_UNAVAILABLE: 503,
  HTTP_STATUS_GATEWAY_TIMEOUT: 504,
  HTTP_STATUS_HTTP_VERSION_NOT_SUPPORT: 505,
  HTTP_STATUS_NSUFFICIENT_STORAGE: 507,
  HTTP_STATUS_HTTP_BANWIDTH_LIMIT_EXCEEDED: 509,
  HTTP_STATUS_NETWORK_AUTHZ_REQUIRED: 511,

  DATE_ISO8601: 'Y-m-d\\TH:i:sO', // Example: 2005-08-15T15:52:01+0000

  OK: 'OK'
};

module.exports = CONSTANT;